version: 2
updates:
  - package-ecosystem: "npm"
    ignore:
      - dependency-name: plyr
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all:
        update-types:
          - "patch"
          - "minor"
