backend:
  name: git-gateway
  branch: master

local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: "sections"
    label: "Sections"
    folder: "src/pages/sections"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          allow_multiple: false,
        }
      - { label: "Content", name: "body", widget: "markdown" }
      - {
          label: "Add sermon manager",
          name: "sermon-manager",
          widget: "boolean",
          default: false,
        }
  - name: "landing"
    label: "Landing"
    files:
      - label: Photo Gallery
        name: photo-gallery
        file: "src/landing/photo-gallery.yml"
        fields:
          - label: Time between photos
            name: time-between-photos
            widget: select
            options:
              - { label: "5 Seconds", value: 5 }
              - { label: "10 Seconds", value: 10 }
              - { label: "15 Seconds", value: 15 }
          - label: Photos
            name: photos
            widget: list
            fields:
              - { label: Image, name: image, widget: image }
      - label: Notice sheet
        name: notice-sheet
        file: "src/landing/notice-sheet.yml"
        fields:
          - label: Text
            name: text
            widget: string
            default: Click here to view the newsletter
          - label: File
            name: file
            widget: file
