backend:
  name: git-gateway
  branch: master

local_backend: true

media_folder: static/assets
public_folder: /assets

collections:
  - name: sections
    label: Sections
    folder: src/sections
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Image
        name: image
        widget: image
        allow_multiple: false
      - label: Content
        name: body
        widget: markdown
      - label: Add sermon manager
        name: sermon-manager
        widget: boolean
        default: false
  - name: settings
    label: Settings
    files:
      - label: Photo gallery
        name: photo-gallery
        file: src/config/photo-gallery.md
        fields:
          - label: Photos
            name: photos
            widget: list
            fields:
              - label: Image
                name: image
                widget: image
      - label: Notice sheet
        name: notice-sheet
        file: src/config/notice-sheet.md
        fields:
          - label: Text
            name: text
            widget: string
            default: Click here to view the newsletter
          - label: File
            name: file
            widget: file
      - name: sectionOrder
        label: Section order
        file: src/config/section-order.md
        fields:
          - label: Order
            name: order
            widget: list
            fields:
              - label: Section
                name: section
                widget: relation
                collection: sections
                searchFields: [title]
                valueField: title
  - name: sermons
    label: Sermons
    folder: src/sermons
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: File
        name: file
        widget: file
      - label: "Published date"
        name: "published"
        widget: "datetime"
        required: false
